FROM python:3.12.7

# Copia o código atualizado do cliente UDP
COPY udp_client.py /app/udp_client.py

# Define o diretório de trabalho
WORKDIR /app

# Executa o cliente UDP
CMD ["python", "udp_client.py"]
