FROM python:3.12.7 AS build

# Cria o diretório /app
RUN mkdir /app

# Copia o arquivo app.py para o diretório /app
COPY app.py /app

# Instala as dependências
RUN pip install flask

# Define o diretório de trabalho
WORKDIR /app

# Comando para executar o app.py
CMD ["python", "app.py"]
